/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef replica_TYPES_H
#define replica_TYPES_H

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>



namespace mp2 {

struct ErrorType {
  enum type {
    NOT_FOUND = 0,
    ALREADY_EXISTS = 1
  };
};

extern const std::map<int, const char*> _ErrorType_VALUES_TO_NAMES;

typedef struct _ReplicaError__isset {
  _ReplicaError__isset() : type(false), name(false), message(false) {}
  bool type;
  bool name;
  bool message;
} _ReplicaError__isset;

class ReplicaError : public ::apache::thrift::TException {
 public:

  static const char* ascii_fingerprint; // = "38C252E94E93B69D04EB3A6EE2F9EDFB";
  static const uint8_t binary_fingerprint[16]; // = {0x38,0xC2,0x52,0xE9,0x4E,0x93,0xB6,0x9D,0x04,0xEB,0x3A,0x6E,0xE2,0xF9,0xED,0xFB};

  ReplicaError() : type((ErrorType::type)0), name(), message() {
  }

  virtual ~ReplicaError() throw() {}

  ErrorType::type type;
  std::string name;
  std::string message;

  _ReplicaError__isset __isset;

  void __set_type(const ErrorType::type val) {
    type = val;
  }

  void __set_name(const std::string& val) {
    name = val;
  }

  void __set_message(const std::string& val) {
    message = val;
  }

  bool operator == (const ReplicaError & rhs) const
  {
    if (!(type == rhs.type))
      return false;
    if (!(name == rhs.name))
      return false;
    if (!(message == rhs.message))
      return false;
    return true;
  }
  bool operator != (const ReplicaError &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ReplicaError & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

void swap(ReplicaError &a, ReplicaError &b);

} // namespace

#endif
