/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef replica_CONSTANTS_H
#define replica_CONSTANTS_H

#include "replica_types.h"

namespace mp2 {

class replicaConstants {
 public:
  replicaConstants();

};

extern const replicaConstants g_replica_constants;

} // namespace

#endif
