/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "replica_constants.h"

namespace mp2 {

const replicaConstants g_replica_constants;

replicaConstants::replicaConstants() {
}

} // namespace

